- src/main/resources/content/tf/AWS-IAM-password-policy-req-lowercase-chars.json
- src/main/resources/content/tf/AWS-IAM-password-policy-req-number.json
- src/main/resources/content/tf/AWS-IAM-password-policy-req-symbol.json
- src/main/resources/content/tf/AWS-IAM-password-policy-req-uppercase-chars.json
- src/test/resources/tf/AWS-IAM-password-policy-req-lowercase-chars-negative.json
- src/test/resources/tf/AWS-IAM-password-policy-req-lowercase-chars-positive.json
- src/test/resources/tf/AWS-IAM-password-policy-req-number-negative.json
- src/test/resources/tf/AWS-IAM-password-policy-req-number-positive.json
- src/test/resources/tf/AWS-IAM-password-policy-req-symbol-negative.json
- src/test/resources/tf/AWS-IAM-password-policy-req-symbol-positive.json
- src/test/resources/tf/AWS-IAM-password-policy-req-uppercase-chars-negative.json
- src/test/resources/tf/AWS-IAM-password-policy-req-uppercase-chars-positive.json
Added positive, negative test cases.
> Isp 105 test:AWS IAM password checks

- src/main/resources/content/cft/AWS-S3-buckets-are-accessible-to-public.json
- src/test/resources/cft/AWS-S3-buckets-are-accessible-to-public/AWS-S3-buckets-are-accessible-to-public-negative.json
- src/test/resources/cft/AWS-S3-buckets-are-accessible-to-public/AWS-S3-buckets-are-accessible-to-public-positive-PublicRead.json
- src/test/resources/cft/AWS-S3-buckets-are-accessible-to-public/AWS-S3-buckets-are-accessible-to-public-positive-PublicReadWrite.json
Removed unnecessary check on WebsiteConfiguration, and added pos / neg cases
> fix(ISP-195): AWS-S3-buckets-are-accessible-to-public

- src/main/resources/content/cft/AWS-S3-buckets-do-not-have-server-side-encryption.json
- src/test/resources/cft/AWS-S3-buckets-do-not-have-server-side-encryption/AWS-S3-buckets-do-not-have-server-side-encryption-negative.json
- src/test/resources/cft/AWS-S3-buckets-do-not-have-server-side-encryption/AWS-S3-buckets-do-not-have-server-side-encryption-positive.json
> fix(ISP-196): AWS-S3-buckets-do-not-have-server-side-encryption

- src/main/resources/content/cft/AWS-VPC-subnets-should-not-allow-automatic-public-IP-assignment.json
- src/test/resources/cft/AWS-VPC-subnets-should-not-allow-automatic-public-IP-assignment/AWS-VPC-subnets-should-not-allow-automatic-public-IP-assignment-negative.json
- src/test/resources/cft/AWS-VPC-subnets-should-not-allow-automatic-public-IP-assignment/AWS-VPC-subnets-should-not-allow-automatic-public-IP-assignment-positive.json
Simplified rule and pos / neg cases.
> fix(ISP-199): AWS VPC subnets should not allow automatic public IP assignment

- src/main/resources/content/cft/AWS-SNS-subscription-is-not-configured-with-HTTPS.json
- src/test/resources/cft/AWS-SNS-subscription-is-not-configured-with-HTTPS/AWS-SNS-subscription-is-not-configured-with-HTTPS-negative.json
- src/test/resources/cft/AWS-SNS-subscription-is-not-configured-with-HTTPS/AWS-SNS-subscription-is-not-configured-with-HTTPS-positive.json
> fix(ISP-197): AWS-SNS-subscription-is-not-configured-with-HTTPS 

- src/main/resources/content/tf/GCP-GKE-clusters-not-configured-with-private-cluster.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-negative-1.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-negative-2.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-negative.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-positive-1.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-positive-2.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-positive-3.json
- src/test/resources/tf/GCP-GKE-clusters-not-configured-with-private-cluster/GCP-GKE-clusters-not-configured-with-private-cluster-positive.json
> ISP-230: GCP-GKE-clusters-not-configured-with-private-cluster

- src/main/resources/content/tf/GCP-Storage-Bucket-are-publicly-accessible-to-allUsers.json
- src/test/resources/tf/GCP-Storage-Bucket-are-publicly-accessible-to-allUsers/GCP-Storage-Bucket-are-publicly-accessible-to-allUsers-negative.json
- src/test/resources/tf/GCP-Storage-Bucket-are-publicly-accessible-to-allUsers/GCP-Storage-Bucket-are-publicly-accessible-to-allUsers-positive.json
> feat(ISP-212)

- src/main/resources/content/tf/GCP-GKE-Cluster-legacy-authorization-enabled.json
- src/test/resources/tf/GCP-GKE-Cluster-legacy-authorization-enabled/GCP-GKE-Cluster-legacy-authorization-enabled-negative.json
- src/test/resources/tf/GCP-GKE-Cluster-legacy-authorization-enabled/GCP-GKE-Cluster-legacy-authorization-enabled-positive.json
> feat(ISP-204): GCP GKE Cluster legacy authorization enabled

- src/main/resources/content/tf/GCP-Kubernetes-Engine-Cluster-Nodes-have-default-Service-accounts-for-project-access.json
- src/main/resources/content/tf/GCP-Kubernetes-Engine-Clusters-Have-Alias-Ip-Disabled.json
- src/test/resources/tf/GCP-Kubernetes-Engine-Clusters-Have-Alias-Ip-Disabled/GCP-Kubernetes-Engine-Clusters-Have-Alias-Ip-Disabled-negative.json
- src/test/resources/tf/GCP-Kubernetes-Engine-Clusters-Have-Alias-Ip-Disabled/GCP-Kubernetes-Engine-Clusters-Have-Alias-Ip-Disabled-positive.json
> feat(ISP-228): Fix typo in one rule and new rule for detecting disabled IP Aliasing in GCP K8s

- src/main/resources/content/tf/GCP-IAM-service-account-has-admin-privileges.json
- src/test/resources/tf/GCP-IAM-service-account-has-admin-privileges/GCP-IAM-service-account-has-admin-privileges-negative-1.json
- src/test/resources/tf/GCP-IAM-service-account-has-admin-privileges/GCP-IAM-service-account-has-admin-privileges-negative.json
- src/test/resources/tf/GCP-IAM-service-account-has-admin-privileges/GCP-IAM-service-account-has-admin-privileges-positive-1.json
- src/test/resources/tf/GCP-IAM-service-account-has-admin-privileges/GCP-IAM-service-account-has-admin-privileges-positive.json
> ISP-200: GCP IAM service account has admin privileges

- src/main/resources/content/tf/GCP-IAM-user-has-service-account-privileges.json
- src/test/resources/tf/GCP-IAM-user-has-service-account-privileges/GCP-IAM-user-has-service-account-privileges-negative-1.json
- src/test/resources/tf/GCP-IAM-user-has-service-account-privileges/GCP-IAM-user-has-service-account-privileges-negative.json
- src/test/resources/tf/GCP-IAM-user-has-service-account-privileges/GCP-IAM-user-has-service-account-privileges-positive-1.json
- src/test/resources/tf/GCP-IAM-user-has-service-account-privileges/GCP-IAM-user-has-service-account-privileges-positive.json
> ISP-202: user has service role

- src/main/resources/content/tf/GCP-IAM-user-have-overly-permissive-KMS-role.json
- src/test/resources/tf/GCP-IAM-user-have-overly-permissive-KMS-role/GCP-IAM-user-have-overly-permissive-KMS-role-negative-1.json
- src/test/resources/tf/GCP-IAM-user-have-overly-permissive-KMS-role/GCP-IAM-user-have-overly-permissive-KMS-role-negative.json
- src/test/resources/tf/GCP-IAM-user-have-overly-permissive-KMS-role/GCP-IAM-user-have-overly-permissive-KMS-role-positive-1.json
- src/test/resources/tf/GCP-IAM-user-have-overly-permissive-KMS-role/GCP-IAM-user-have-overly-permissive-KMS-role-positive.json
> ISP-201: check is user is assigned overly permissive KMS roles

- src/main/resources/content/tf/Azure-SQL-Server-advanced-data-security-is-disabled.json
- src/test/resources/tf/Azure-SQL-Server-advanced-data-security-is-disabled/Azure-SQL-Server-advanced-data-security-is-disabled-negative-all-state-enabled-with-retentions.json
- src/test/resources/tf/Azure-SQL-Server-advanced-data-security-is-disabled/Azure-SQL-Server-advanced-data-security-is-disabled-negative-no-sql-server.json
- src/test/resources/tf/Azure-SQL-Server-advanced-data-security-is-disabled/Azure-SQL-Server-advanced-data-security-is-disabled-positive-missing-alert-policy.json
- src/test/resources/tf/Azure-SQL-Server-advanced-data-security-is-disabled/Azure-SQL-Server-advanced-data-security-is-disabled-positive-missing-retention-days.json
- src/test/resources/tf/Azure-SQL-Server-advanced-data-security-is-disabled/Azure-SQL-Server-advanced-data-security-is-disabled-positive-policy-disabled.json
> SL-210: azure sql server advanced data security

- src/main/resources/content/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled.json
- src/test/resources/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled-negative-both-bypass-AzureServices.json
- src/test/resources/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled-negative-no-storage-account.json
- src/test/resources/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled-positive-both-network-rules-missing.json
- src/test/resources/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled-positive-bypass-is-None.json
- src/test/resources/tf/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled/Azure-Storage-Account-Trusted-Microsoft-Services-access-not-enabled-positive-one-network-rules-missing.json
> SL-206: Azure storage accounts network_rules bypass trusted services

- src/main/resources/content/tf/Azure-App-Service-Web-App-doesnt-redirect-http-to-https.json
- src/test/resources/tf/Azure-App-Service-Web-App-doesnt-redirect-http-to-https/Azure-App-Service-Web-App-doesnt-redirect-http-to-https-negative.json
- src/test/resources/tf/Azure-App-Service-Web-App-doesnt-redirect-http-to-https/Azure-App-Service-Web-App-doesnt-redirect-http-to-https-positive.json
> feat(SL-205): Azure App Service Web App HTTPS Only

- src/main/resources/content/tf/Azure-AKS-enable-RBAC-not-enforced.json
- src/test/resources/tf/Azure-AKS-enable-RBAC-not-enforced/Azure-AKS-enable-RBAC-not-enforced-negative-both-enabled.json
- src/test/resources/tf/Azure-AKS-enable-RBAC-not-enforced/Azure-AKS-enable-RBAC-not-enforced-negative-no-AKS.json
- src/test/resources/tf/Azure-AKS-enable-RBAC-not-enforced/Azure-AKS-enable-RBAC-not-enforced-positive-AKS-RBAC-false.json
- src/test/resources/tf/Azure-AKS-enable-RBAC-not-enforced/Azure-AKS-enable-RBAC-not-enforced-positive-AKS-RBAC-missing.json
- src/test/resources/tf/Azure-AKS-enable-RBAC-not-enforced/Azure-AKS-enable-RBAC-not-enforced-positive-both-AKS-RBAC-missing.json
> SL-208: AKS RBAC not enabled

- src/main/resources/content/tf/Azure-App-Service-Web-App-no-managed-service-identity.json
- src/test/resources/tf/Azure-App-Service-Web-App-no-managed-service-identity/Azure-App-Service-Web-App-no-managed-service-identity-negative-has-identity.json
- src/test/resources/tf/Azure-App-Service-Web-App-no-managed-service-identity/Azure-App-Service-Web-App-no-managed-service-identity-negative-no-app-service.json
- src/test/resources/tf/Azure-App-Service-Web-App-no-managed-service-identity/Azure-App-Service-Web-App-no-managed-service-identity-positive-both-missing-identity.json
- src/test/resources/tf/Azure-App-Service-Web-App-no-managed-service-identity/Azure-App-Service-Web-App-no-managed-service-identity-positive-with-one-missing-identity.json
> SL-198: azure app without identity

- src/main/resources/content/tf/Azure-App-Service-Web-app-authentication-off.json
- src/test/resources/tf/Azure-App-Service-Web-app-authentication-off/Azure-App-Service-Web-app-authentication-off-negative-NO-app-service.json
- src/test/resources/tf/Azure-App-Service-Web-app-authentication-off/Azure-App-Service-Web-app-authentication-off-negative-app-auth-enabled.json
- src/test/resources/tf/Azure-App-Service-Web-app-authentication-off/Azure-App-Service-Web-app-authentication-off-positive-app-missing-auth-settings.json
- src/test/resources/tf/Azure-App-Service-Web-app-authentication-off/Azure-App-Service-Web-app-authentication-off-positive-auth-disabled.json
> SL-197: check azure app auth enabled

- src/main/resources/content/tf/Azure-Network-Security-Group-allow-port-3389-inbound.json
- src/test/resources/tf/Azure-Network-Security-Group-allow-port-3389-inbound/Azure-Network-Security-Group-allow-port-3389-inbound-negative-N-3389.json
- src/test/resources/tf/Azure-Network-Security-Group-allow-port-3389-inbound/Azure-Network-Security-Group-allow-port-3389-inbound-negative-No-NSG-rule.json
- src/test/resources/tf/Azure-Network-Security-Group-allow-port-3389-inbound/Azure-Network-Security-Group-allow-port-3389-inbound-positive-destination_port_range-is-3389.json
- src/test/resources/tf/Azure-Network-Security-Group-allow-port-3389-inbound/Azure-Network-Security-Group-allow-port-3389-inbound-positive-destination_port_ranges-contains-3389.json
> SL-196: azure network_security_rule allows 3389 inbound

- src/test/java/io/redlock/iac/ContentTest.java
- src/test/java/io/redlock/iac/Rule.java
> mandate the description in rule creation

- src/main/resources/content/tf/Azure-App-Service-Web-app-TLS-version-not-latest.json
- src/test/resources/tf/Azure-App-Service-Web-app-TLS-version-not-latest/Azure-App-Service-Web-app-TLS-version-not-latest-negative-no-app-service.json
- src/test/resources/tf/Azure-App-Service-Web-app-TLS-version-not-latest/Azure-App-Service-Web-app-TLS-version-not-latest-negative-tls-min-version-default-or-1dot2.json
- src/test/resources/tf/Azure-App-Service-Web-app-TLS-version-not-latest/Azure-App-Service-Web-app-TLS-version-not-latest-positive-both-tls-min-version-bad.json
- src/test/resources/tf/Azure-App-Service-Web-app-TLS-version-not-latest/Azure-App-Service-Web-app-TLS-version-not-latest-positive-one-tls-min-version-bad.json
> SL-204: Azure App Service Web app doesn't use latest TLS version

- src/main/resources/content/tf/Azure-Virtual-Machine-no-endpoint-protection-installed.json
- src/test/resources/tf/Azure-Virtual-Machine-no-endpoint-protection-installed/Azure-Virtual-Machine-no-endpoint-protection-installed-negative-has-EndpointSecurity-extension.json
- src/test/resources/tf/Azure-Virtual-Machine-no-endpoint-protection-installed/Azure-Virtual-Machine-no-endpoint-protection-installed-negative-no-VM.json
- src/test/resources/tf/Azure-Virtual-Machine-no-endpoint-protection-installed/Azure-Virtual-Machine-no-endpoint-protection-installed-positive-no-VM-extension.json
- src/test/resources/tf/Azure-Virtual-Machine-no-endpoint-protection-installed/Azure-Virtual-Machine-no-endpoint-protection-installed-positive-not-found-pattern-in-extension-type.json
> SL-216: security VM extension

- src/main/resources/content/tf/Azure-Key-Vault-Keys-have-no-expiration-date.json
- src/test/resources/tf/Azure-Key-Vault-Keys-have-no-expiration-date/Azure-Key-Vault-Keys-have-no-expiration-date-negative-have-expiration.json
- src/test/resources/tf/Azure-Key-Vault-Keys-have-no-expiration-date/Azure-Key-Vault-Keys-have-no-expiration-date-negative-no-secrets.json
- src/test/resources/tf/Azure-Key-Vault-Keys-have-no-expiration-date/Azure-Key-Vault-Keys-have-no-expiration-date-positive-both-missing-expiration.json
- src/test/resources/tf/Azure-Key-Vault-Keys-have-no-expiration-date/Azure-Key-Vault-Keys-have-no-expiration-date-positive-one-missing-expiration.json
> SL-213: Azure Key Vault Secrets have no expiration date

- src/main/resources/content/tf/Azure-Storage-Account-default-network-access-set-to-Allow.json
- src/test/resources/tf/Azure-Storage-Account-default-network-access-set-to-Allow/Azure-Storage-Account-default-network-access-set-to-Allow-negative-all-default-action-Deny.json
- src/test/resources/tf/Azure-Storage-Account-default-network-access-set-to-Allow/Azure-Storage-Account-default-network-access-set-to-Allow-negative-no-storage-account.json
- src/test/resources/tf/Azure-Storage-Account-default-network-access-set-to-Allow/Azure-Storage-Account-default-network-access-set-to-Allow-positive-1-network-rule-Allow.json
- src/test/resources/tf/Azure-Storage-Account-default-network-access-set-to-Allow/Azure-Storage-Account-default-network-access-set-to-Allow-positive-1-storage-account-network-rule-Allow.json
> SL-207: Azure Storage Account default network access is set to Allow
